name: cool_background_animation
description: "A Flutter package for stunning and customizable background animations."
version: 0.1.0
homepage: https://github.com/AIdevol/cool_background_animation

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
# Example assets (uncomment if you use any):
# assets:
#   - images/example_image_1.png
#   - images/example_image_2.png

# Example fonts (uncomment if you use custom fonts):
# fonts:
#   - family: MyCustomFont
#     fonts:
#       - asset: fonts/MyCustomFont-Regular.ttf
#       - asset: fonts/MyCustomFont-Bold.ttf
#         weight: 700
